language: go

# The feature/go15 branch uses new features in go15. Only testing this branch
# against tip which has the features.
go:
  - 1.5
  - 1.6
  - 1.7
  - master

deploy:
  provider: gae
  keyfile: "YOUR SERVICE ACCOUNT JSON FILE"
  project: "YOUR PROJECT ID"